### PR TITLE
add collection in lastEvent query

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] add collection in lastEvent https://github.com/kodadot/nft-gallery/issues/3927#issue-1366497409

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [x] My contribution is a **resolver** so I have pic from playground
Screen Shot 2022-09-12 at 19 46 32

### CODE REVIEW

**Comment by preschian** [comment]
cc @roiLeo @vikiival requesting a review
I'm unable to edit reviewers through GitHub panel
Screen Shot 2022-09-12 at 19 52 41

changed files under `src/model/generated` are coming from `just codegen`, is that expected?

**Comment by roiLeo** [comment]
ref kodadot/snek#64, looks good

> changed files under `src/model/generated` are coming from `just codegen`, is that expected?

I have no idea about this point

**Comment by vikiival** [comment]
> changed files under src/model/generated are coming from just codegen, is that expected?

it should not change tbh

**Comment by preschian** [comment]
> it should not change tbh

reverted those files 👌

**Pull request merged**
