### PR TITLE
Release v9

### LINKED ISSUE #261: Release Rubick v9

### PR DESCRIPTION
**Pull request by Matehoo**
**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #261 
- [ ] This PR is required for kodadot/nft-gallery#<issue_number>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [X] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/ksm/transfer?target=GJ8Zm8qRdhHeDeGY6ADW7DtVyjaiwTpGkNanekSCQVmXidP&usdamount=100&donation=true)

### Optional

- [ ] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [ ] My contribution is a **resolver** so I have pic from playground

### CODE REVIEW

**Comment by Matehoo** [comment]
@vikiival pls review

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Comment by vikiival** [comment]
@yangwao can we neble bot so in other repos?

**Comment by vikiival** [comment]
cc @yangwao

**Pull request merged**
