### PR TITLE
Release 008

### PR DESCRIPTION
**Pull request by roiLeo**

### CODE REVIEW

**Comment by yangwao** [comment]
oh, it's tied to the name branch got it!

**Comment by roiLeo** [comment]
> oh, it's tied to the name branch got it!

and you'll have to run command "Authenticate and deploy" ping @vikiival

**Comment by vikiival** [comment]
Looks like it was deployed successfully 

https://github.com/kodadot/rubick/actions/runs/3847626699/jobs/6554319605

Did I miss something?

**Comment by roiLeo** [comment]
> Looks like it was deployed successfully
> 
> https://github.com/kodadot/rubick/actions/runs/3847626699/jobs/6554319605
> 
> Did I miss something?

my bad didn't knew you created a CI

**Comment by yangwao** [comment]
> my bad didn't knew you created a CI

glory to @preschian

**Pull request merged**
