### PR TITLE
Revert "203 resources on last event query for rmrk2"

### PR DESCRIPTION
**Pull request by vikiival**
Reverts kodadot/rubick#225

### CODE REVIEW

**Comment by vikiival** [comment]
cc @Matehoo I am unable run graphql server since this commit

**Comment by Matehoo** [comment]
Do you have some errors/logs?

**Comment by vikiival** [comment]
:D Yeah it was my issue, i made an entity called `Resource` and you already had entity called `Resource` therefore it was failing

**Comment by Matehoo** [comment]
Got it, maybe in the future I should always create new model file if i am adding field that has entity

**Pull request closed without merging**
