### PR TITLE
feat: deploy/update subsquid from gh actions

### LINKED ISSUE #38: Auto publish Squid
Create a branch (e.g `005`)
Gh action should update the squid (`just improve 005`)

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #38
- add auto deploy/update to subsquid from `release-***` branch pattern
- need to add `DEPLOYMENT_KEY` as GitHub secrets
- tested in https://github.com/preschian/rubick/pull/5/checks

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [ ] My contribution is a **resolver** so I have pic from playground

### CODE REVIEW

**Comment by vikiival** [comment]
> oops sorry, I thought this bot only works on [nft-gallery](https://github.com/kodadot/nft-gallery/)

I see it for the first time here.
All indexers repository are like a dark side of a club 😅

Soo any `manual for this`?

**Comment by preschian** [comment]
> I see it for the first time here.
> All indexers repository are like a dark side of a club 😅

🙈

> Soo any manual for this?

- add `DEPLOYMENT_KEY` in Github secrets
- the `actions` will trigger if the branch name with the prefix `release-`
- from `release-007` turn into `name@007` in subsquid
- if the version is newly created, it will run subsquid with `release` command
- if the version already exists, it will run subsquid with `update` command

btw, I forgot to remove the `test` name, will update it https://github.com/kodadot/rubick/pull/120/files#diff-eb331ca122c53a2ab9c5719f6b02f606c0346be74b43105be5d4c7a3c34ea5ccR27

**Comment by vikiival** [comment]
added `DEPLOYMENT_KEY` let's merge it

**Comment by vikiival** [comment]
https://github.com/kodadot/rubick/runs/7802771314?check_suite_focus=true

**Pull request merged**
