### PR TITLE
talk charty to me

### PR DESCRIPTION
**Pull request by vikiival**
- :construction: collection chart resolver
- :zap: working chart

### CODE REVIEW

**Comment by vikiival** [comment]
@yangwao for almost each day we have:

max price
average price
and count of sales

Am I missing anything?
I think we were also thinking about sum

**Comment by yangwao** [comment]
floors is still there?

**Comment by yangwao** [comment]
Floor price yup

**Comment by vikiival** [comment]
I can extend query (would be bit slower but yolo)

**Comment by yangwao** [comment]
yup it can help you see how much greedy was holders/creators

image

**Pull request merged**
