### PR TITLE
last event support passion list

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [x] This PR is required for kodadot/nft-gallery#3239

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [x] My contribution is a **resolver** so I have pic from playground
image

image

### CODE REVIEW

**Review by vikiival — APPROVED** [review]
3.6

**Comment by vikiival** [comment]
Thinking if we shouldnt do it otherwise ? 
Have you tested that on people that have more items ?

**Comment by Jarsen136** [comment]
>Thinking if we shouldnt do it otherwise ?

It's what we have done with subquery in graphql. Or is there any better solution?
image


> Have you tested that on people that have more items ?

How about 10 address. It still works well and fast.
image

**Comment by Jarsen136** [comment]
> > Or is there any better solution?
> 
> maybe have argument passion: Boolean and fetch passion that data directly in resolver

I'm not sure if it would be better, because the resolver need to request passion list through accountId, and then request `lastEvent`. It seems costs more time 👀  
Please correct me if I understand wrong.


> And If you provide like 300 of them wouldn't the query `request` fail?

In this case, I guess the query would fail : )

**Comment by Jarsen136** [comment]
> Yeah you are right, but I just want to avoid case when person with a lot of buys breaks the query

It makes sense.

**Comment by Jarsen136** [comment]
updated!


image

image

**Comment by vikiival** [comment]
I gave also merging rights to @kodadot/autocode so @petersopko can review and merge too

**Comment by Jarsen136** [comment]
Hey there, pls take a look at this PR if you have time. ❤️   @petersopko

**Comment by petersopko** [comment]
> Hey there, pls take a look at this PR if you have time. ❤️ @petersopko

took a look, tested it out, lgtm

**Pull request merged**
