### PR TITLE
169 no buy for you

### LINKED ISSUE #169: Cached entities do not work
on `release-007` I tried:

```ts
processor.setBlockRange({from:5756453, to: 7479313});
```

got result

```sql
 squid=# select count(*) from series ;
  count
 -------
     17
```

For 008 it does not work

### PR DESCRIPTION
**Pull request by vikiival**
- :wrench: max root fields set for 50
- :zap: reverse engineer collection id
- :bug: fetching of collection from NFT

**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #169
- [ ] This PR is required for kodadot/nft-gallery#<issue_number>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [ ] My contribution is a **resolver** so I have pic from playground

### CODE REVIEW

**Comment by vikiival** [comment]
[I also asked in the telegram group if we can make it your way.](https://t.me/HydraDevs/4623)

**Review by roiLeo — APPROVED** [review]
✅ wfm until KAN blocks 
Capture d’écran 2023-01-09 à 8 51 33 AM

**Comment by vikiival** [comment]
> until KAN blocks '
It means that you tried that until kan?

**Comment by roiLeo** [comment]
> It means that you tried that until kan?

Yessir! Stopped at around block `6802508`

**Comment by vikiival** [comment]
Made issue to make DX more seamless

https://github.com/kodadot/packages/issues/87

**Pull request merged**
